### ISSUE TITLE
Add bors to this project

### ISSUE THREAD

**Issue by peterbe** [mozilla/buildhub2#170]
Most important; a note in README or dev.rst about how to *use* it :)

* [x] Add bors integration to repo ([Bug 1479830](https://bugzilla.mozilla.org/show_bug.cgi?id=1479830))
* [x] Add do not merge tag
* [x] Add bors config
* [x] Add development instructions
* [x] Make bors mandatory

**Comment by mythmon** [comment]
#171 has merged, and I've configured this repo to require bors to merge a PR. Administrators can override this, in needed.
