### ISSUE TITLE
Warning on JSONField callable default in Django 2.1

### ISSUE THREAD

**Issue by bqbn** [mozilla/buildhub2#274]
When running `./manage.py reindex-elasticsearch` to create the `buildhub2` index for the first time, we ran into the following warning message.

```
$ ./manage.py reindex-elasticsearch
{"Timestamp": 1536193993444640512, "Type": "markus.backends.datadog", "Logger": "buildhub", "Hostname": "ip-172-31-2-154", "EnvVersion": "2.0", "Severity": 6, "Pid": 8, "Fields": {"msg": "DatadogMetrics configured: localhost:8125 "}}
System check identified some issues:

WARNINGS:
main.Build.metadata: (postgres.E003) JSONField default should be a callable instead of an instance so that it's not shared between all field instances.
	HINT: Use a callable instead, e.g., use `dict` instead of `{}`.
Force merged Elasticsearch index after bulk insert
```

Fwiw, despite of the above warning, the `buildhub2` index was created successfully (it seems like).

Not sure how serious the warning message is or if you want to fix it or not.

**Comment by peterbe** [comment]
Ah. It's just a future warning that was introduced in Django 2.1. Unrelated to elasticsearch. Just that it happens when you run anything `./manage.py`.

I've changed my local dev environment to catch these kinds of things earlier.
