### ISSUE TITLE
Help Socorro migrate

### ISSUE THREAD

**Issue by willkg** [mozilla/buildhub2#366]
https://github.com/mozilla-services/socorro/blob/8adaee728c9d960fb6613260c053720bcdfb799f/socorro/processor/processor_2015.py#L120

**Comment by peterbe** [comment]
Also, in this admin function thing: https://github.com/mozilla-services/socorro/blob/69b9a0cd6293c2d4c90b624060068650d9f92c94/webapp-django/crashstats/manage/admin.py#L240

**Comment by peterbe** [comment]
As of today, neither https://github.com/mozilla-services/socorro/blob/master/socorro/processor/processor_2015.py nor https://github.com/mozilla-services/socorro/blob/master/webapp-django/crashstats/manage/admin.py is even mentioning `buildhub`. 

However, https://github.com/mozilla-services/socorro/blob/e2be264c1fc4e4d045069cd4de5b41cdfe160631/webapp-django/crashstats/settings/base.py#L390 still does.

**Comment by peterbe** [comment]
I made a PR with the GitHub web UI: https://github.com/mozilla-services/socorro/pull/4846
