### ISSUE TITLE
Require "build" in JSON Schema

### ISSUE THREAD

**Issue by peterbe** [mozilla/buildhub2#370]
[At the moment, "build" is **not** a required key](https://github.com/mozilla/buildhub2/blob/d00789fcbbf967fcd32fb142e824fc33deec184d/schema.yaml#L6-L9).

This is rather odd. All *valid* records on Buildhub Prod (the legacy one) have a "build" key.

**Comment by peterbe** [comment]
@leplatrem Thoughts on this?

**Comment by leplatrem** [comment]
> @leplatrem Thoughts on this?

I can't really explain it. It should be required, since it's the whole point of the API ;)
