### ISSUE TITLE
Buildhub2 daemon process failed to start

### ISSUE THREAD

**Issue by bqbn** [mozilla/buildhub2#383]
So the buildhub2 daemon process, the one that is used to process SQS messages, failed to start with the following error:

```
Nov 17 03:24:24 ip-172-31-21-134.ec2.internal systemd[1]: Started Daemon for process-sqs-queue.
Nov 17 03:24:26 ip-172-31-21-134.ec2.internal docker-process-sqs-queue[2794]: Not waiting for any services
Nov 17 03:24:31 ip-172-31-21-134.ec2.internal docker-process-sqs-queue[2794]: {"Timestamp": 1542425071456798976, "Type": "markus.backends.datadog", "Logger": "buildhub", "Hostname": "ip-172-31-21-134.ec2.internal", "EnvVersion": "2.0", "Severity": 6, "Pid": 1, "Fields": {"msg": "DatadogMetrics configured: localhost:8125 "}}
Nov 17 03:24:31 ip-172-31-21-134.ec2.internal docker-process-sqs-queue[2794]: {"Timestamp": 1542425071458414848, "Type": "raven.contrib.django.client.DjangoClient", "Logger": "buildhub", "Hostname": "ip-172-31-21-134.ec2.internal", "EnvVersion": "2.0", "Severity": 7, "Pid": 1, "Fields": {"msg": "Configuring Raven for host: https://sentry.prod.mozaws.net"}}
Nov 17 03:24:31 ip-172-31-21-134.ec2.internal docker-process-sqs-queue[2794]: SystemCheckError: System check identified some issues:
Nov 17 03:24:31 ip-172-31-21-134.ec2.internal docker-process-sqs-queue[2794]: ERRORS:
Nov 17 03:24:31 ip-172-31-21-134.ec2.internal docker-process-sqs-queue[2794]: ?: (buildhub.health.E003) You do not have access to read net-mozaws-prod-delivery-inventory-us-east-1. From https://s3.amazonaws.com/net-mozaws-prod-delivery-inventory-us-east-1
Nov 17 03:24:32 ip-172-31-21-134.ec2.internal systemd[1]: docker-process-sqs-queue.service: main process exited, code=exited, status=1/FAILURE
```

Note that `net-mozaws-prod-delivery-inventory-us-east-1` is a public bucket and can be read by anyone on the internet. Thus, this error probably means some code needs the same treatment as in https://github.com/mozilla/buildhub2/pull/382.

It's worth mentioning that the main buildhub2 app starts up fine, as usual. I'm not sure why though, maybe you have an explanation?

**Comment by peterbe** [comment]
It was only just last week I learned about unsigned requests. I wonder if there's a difference in permissions between reading an object and other ops like `boto_client.head_bucket(Bucket='my-bucket-name')`. You know, just like Nginx/Apache will allow you to GET any file but doesn't allow you to get an index of all files per directory.

What settings do you have set for `DJANGO_S3_BUCKET_URL` and `DJANGO_SQS_S3_BUCKET_URL`?

**Comment by bqbn** [comment]
I think it is https://github.com/mozilla/buildhub2/blob/master/buildhub/dockerflow_extra.py#L90 that needs the same treatment in https://github.com/mozilla/buildhub2/pull/382.


DJANGO_S3_BUCKET_URL is set to `https://s3.amazonaws.com/net-mozaws-prod-delivery-inventory-us-east-1`, whereas DJANGO_SQS_S3_BUCKET_URL is not set at the moment (i.e. the bucket name is obtained from SQS message).

**Comment by peterbe** [comment]
I'm unable to reproduce this. It's quite possibly because my aws credentials are very different. 

So, here's what I have:

1. In my .env I have credentials for reading the SQS queue for testing: `https://sqs.us-west-2.amazonaws.com/927034868273/buildhub-s3-events`

2. In my .env I have this set up: `DJANGO_SQS_S3_BUCKET_URL=https://s3.amazonaws.com/net-mozaws-prod-delivery-inventory-us-east-1`

3. When Django does its startup healthchecks, it checks, *without any UNSIGNED* that I can `head_bucket('net-mozaws-prod-delivery-inventory-us-east-1')`. It works! See:

```
In [1]: import boto3

In [2]: s3_client = boto3.client('s3', "us-east-1")
INFO 2018-11-20 02:03:00,343 botocore.credentials Found credentials in environment variables.

In [3]: s3_client.head_bucket(Bucket='net-mozaws-prod-delivery-inventory-us-east-1')
Out[3]:
{'ResponseMetadata': {'RequestId': '82AB98FC6B3F4B19',
  'HostId': '0a/RYAcYepwu5P8OSuQREcjqMJIiDBnndnHYhmJciHYR7FHVskIY+ASGrkp2b4jMhBDooHA+Ka8=',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amz-id-2': '0a/RYAcYepwu5P8OSuQREcjqMJIiDBnndnHYhmJciHYR7FHVskIY+ASGrkp2b4jMhBDooHA+Ka8=',
   'x-amz-request-id': '82AB98FC6B3F4B19',
   'date': 'Tue, 20 Nov 2018 02:03:31 GMT',
   'x-amz-bucket-region': 'us-east-1',
   'content-type': 'application/xml',
   'transfer-encoding': 'chunked',
   'server': 'AmazonS3'},
  'RetryAttempts': 0}}
```

In other words, without credentials made for that S3 bucket (the big beast S3 bucket that Mozilla RelEng writes builds to), I can run `head_bucket` on it without unsigned. 

4. Inside the daemon code, when it gets a test payload, I manually override the bucket name:

```python
def process_buildhub_json_key(config, s3):
    logger.debug(f"S3 buildhub.json key {s3!r}")
    key_name = s3["object"]["key"]
    assert os.path.basename(key_name).endswith("buildhub.json"), key_name
    bucket_name = s3["bucket"]["name"]
    bucket_name = "net-mozaws-prod-delivery-inventory-us-east-1"  # HACKING!
    ...
```

That "works"! Granted, the S3 key that the SQS payload mentioned doesn't exist so I get a 404 and a logging warning. 

**In conclusion...**

* In my Django healtcheck I can connect to that real hardcoded S3 RelEng bucket. 
* In my daemon I can attempt to download files from that hardcoded S3 RelEng bucket. 
* Nowhere do I have "the right credentials" for it. In my `.env` file I have the AWS Dev credentials for consuming `https://sqs.us-west-2.amazonaws.com/927034868273/buildhub-s3-events`. In my personal `~/.aws/credentials` (under `[default]`) I have the IAM Dev credentials necessary for being along to *write* to `https://sqs.us-west-2.amazonaws.com/927034868273/buildhub-s3-events` with my little Go client. 
* The code in `master` uses an UNSIGNED connection to do the S3 download (from the SQS payload). 

Why can I do a `head_bucket` against that S3 bucket when I don't have the right credentials for it? What kind of credentials did you create?

**Comment by peterbe** [comment]
> DJANGO_S3_BUCKET_URL is set to https://s3.amazonaws.com/net-mozaws-prod-delivery-inventory-us-east-1, whereas DJANGO_SQS_S3_BUCKET_URL is not set at the moment (i.e. the bucket name is obtained from SQS message).

Yes. This is correct. I just don't understand why that's working for me but not for you. I guess we can just use unsigned requests for the healthcheck to see if that solves all the problems.

**Comment by peterbe** [comment]
I THINK I GET IT NOW!

Maybe.

You see, there are actually three different buckets! One for the TaskCluster builds (`net-mozaws-prod-delivery-firefox` and `net-mozaws-prod-delivery-archive`) and one just for the inventory (`net-mozaws-prod-delivery-inventory-us-east-1`)

In Buildhub1, the scraper cron job would read the `net-mozaws-prod-delivery-inventory-us-east-1` bucket too download 150'ish .csv.gz files. These CSV files contains the entire lists of every single S3 key. When you read the CSV files, the first column is a/the bucket name and the second column is the key name. 

I downloaded all the CSV files and determined that the only buckets are "net-mozaws-prod-delivery-firefox" or "net-mozaws-prod-delivery-archive". 

So, to start with [this](https://github.com/mozilla/buildhub2/blob/579f69b54e3b8ebf6f6c8f4cee89eeaf93730898/buildhub/settings.py#L26-L29) is not only wrong, it also means that the `DJANGO_S3_BUCKET_URL` needs to become `DJANGO_S3_BUCKET_URLS` instead.

**Comment by bqbn** [comment]
> Why can I do a head_bucket against that S3 bucket when I don't have the right credentials for it?

One way to re-produce it is to run the following two commands locally,

```
docker run --rm hub.prod.mozaws.net/pipelines/buildhub2/buildhub2:latest python -c 'import boto3; s3_client = boto3.client("s3", "us-east-1"); s3_client.head_bucket(Bucket="net-mozaws-prod-delivery-inventory-us-east-1")'
```
and

```
docker run --rm hub.prod.mozaws.net/pipelines/buildhub2/buildhub2:latest python -c 'import boto3; from botocore import UNSIGNED; from botocore.client import Config; s3_client = boto3.client("s3", "us-east-1", config=Config(signature_version=UNSIGNED)); s3_client.head_bucket(Bucket="net-mozaws-prod-delivery-inventory-us-east-1")'
```

And then you should be able to see the difference.

The point is that the error happens inside the container, not outside the container. If I had to guess, it could be that the local boto3/botocore versions are different from what's in the docker image.

**Comment by bqbn** [comment]
> First of all, that bucket is now considered the wrong one. We need to start using net-mozaws-prod-delivery-firefox. I have a PR about switching to that.

That's good to know. Note that `net-mozaws-prod-delivery-firefox` is also a public bucket.

> What matters is the AWS_* credentials.

IMHO, when talking to public S3 buckets, we should really leverage that `UNSIGNED` flag as it is done in https://github.com/mozilla/buildhub2/pull/382, and not give the application any AWS_* credentials. Assigning any AWS_* credentials to the app such that it may have more access than it needs is against the [principle of least privilege](https://en.wikipedia.org/wiki/Principle_of_least_privilege), and is usually not a good practice.

**Comment by peterbe** [comment]
See https://github.com/mozilla/buildhub2/pull/390

Everywhere it now uses unsigned requests for all S3 access. The startup check, the backfill, and the SQS stuff.
